"""firehose_status — operations report for the free wallet firehose (PHASE 1 hardening).

Reads _data/firehose.sqlite3 and prints (and writes FIREHOSE_STATUS.md):
  * source-health summary: trades/wallets/tokens/pools, duplicate rate, rate-limits, parse fails, confidence
  * daily rollup: per-calendar-day trades/wallets/tokens
  * collection-target: days needed for H-162 day-level OOS, expected events/day, min viable n

Run: py hypothesis_lab/wallet_alpha/firehose_status.py [--write]
"""
from __future__ import annotations

import sqlite3
import sys
from datetime import datetime, timezone

from firehose_collector import DB

# H-162 day-level OOS target (from H162_PERSISTENCE_REPORT + CONSTRAINTS gate n>100):
MIN_DAYS = 14                 # distinct calendar days to separate cross-sectional skill from regime
IDEAL_DAYS = 30
MIN_SELLCLUSTER_PER_DAY = 100  # n>100 independent sell-cluster events per day for a day-level gate
# empirical: on the bitquery firehose (803k trades/5.5h) ~975 sell-clusters formed. GeckoTerminal free is
# far thinner; we estimate clusters/day from observed trades and the cluster yield ratio below.
CLUSTER_YIELD = 975 / 803_000   # sell-cluster events per raw trade (May-14 reference)


def _q(db, sql, *a):
    return db.execute(sql, a).fetchone()


def summary(db) -> dict:
    n = _q(db, "SELECT COUNT(*) FROM firehose_trades")[0]
    w = _q(db, "SELECT COUNT(DISTINCT wallet) FROM firehose_trades")[0]
    tok = _q(db, "SELECT COUNT(DISTINCT token_mint) FROM firehose_trades")[0]
    pool = _q(db, "SELECT COUNT(DISTINCT pool_address) FROM firehose_trades")[0]
    rng = _q(db, "SELECT MIN(block_ts), MAX(block_ts) FROM firehose_trades")
    runs = _q(db, "SELECT COUNT(*), COALESCE(SUM(trades_seen),0), COALESCE(SUM(trades_new),0), "
                  "COALESCE(SUM(http_fail),0), COALESCE(SUM(rate_limited),0) FROM firehose_runs")
    n_runs, seen, new, fail, rl = runs
    dup_rate = (1 - new / seen) if seen else 0.0
    span_d = ((rng[1] - rng[0]) / 86400.0) if rng[0] and rng[1] else 0.0
    return {"trades": n, "wallets": w, "tokens": tok, "pools": pool, "span_days": span_d,
            "runs": n_runs, "seen": seen, "new": new, "dup_rate": dup_rate, "http_fail": fail,
            "rate_limited": rl, "confidence": "medium (real on-chain fills; GeckoTerminal free)"}


def daily(db):
    return db.execute(
        "SELECT date(block_ts,'unixepoch') d, COUNT(*), COUNT(DISTINCT wallet), COUNT(DISTINCT token_mint) "
        "FROM firehose_trades WHERE block_ts IS NOT NULL GROUP BY d ORDER BY d").fetchall()


def target(s: dict) -> dict:
    days_have = len(set())  # filled by caller via daily()
    trades_per_day = (s["trades"] / s["span_days"]) if s["span_days"] > 0.05 else float(s["trades"])
    est_clusters_day = trades_per_day * CLUSTER_YIELD
    days_to_min_n = (MIN_SELLCLUSTER_PER_DAY / est_clusters_day) if est_clusters_day > 0 else float("inf")
    return {"trades_per_day_est": trades_per_day, "est_sellclusters_per_day": est_clusters_day,
            "min_sellclusters_per_day": MIN_SELLCLUSTER_PER_DAY, "min_days": MIN_DAYS, "ideal_days": IDEAL_DAYS,
            "days_to_reach_min_n_per_day": days_to_min_n}


def render_md(s, d, t) -> str:
    dtr = t["days_to_reach_min_n_per_day"]
    days_str = "OK now" if dtr <= 1 else (f"~{dtr:.0f} loop-days of accumulation" if dtr != float("inf") else "n/a (no data yet)")
    lines = [f"# FIREHOSE STATUS — {datetime.now(timezone.utc).isoformat()}", "",
             "Auto-generated by `firehose_status.py`. Source: `_data/firehose.sqlite3` (free GeckoTerminal).", "",
             "## Source health",
             f"- trades: **{s['trades']:,}** | wallets: {s['wallets']:,} | tokens: {s['tokens']:,} | pools: {s['pools']:,}",
             f"- calendar span: **{s['span_days']:.2f} days** | runs: {s['runs']}",
             f"- duplicate rate: {s['dup_rate']:.1%} (seen {s['seen']:,} -> new {s['new']:,})",
             f"- rate-limits: {s['rate_limited']} | http failures: {s['http_fail']} | confidence: {s['confidence']}", "",
             "## Daily rollup", "", "| day | trades | wallets | tokens |", "|---|---|---|---|"]
    for row in d:
        lines.append(f"| {row[0]} | {row[1]:,} | {row[2]:,} | {row[3]:,} |")
    lines += ["", "## Collection target (H-162 day-level OOS)",
              f"- distinct days collected: **{len(d)}** / min **{t['min_days']}** (ideal {t['ideal_days']})",
              f"- est trades/day at current rate: {t['trades_per_day_est']:,.0f}",
              f"- est sell-cluster events/day: **{t['est_sellclusters_per_day']:.1f}** "
              f"(need >= {t['min_sellclusters_per_day']} for a day-level n>100 gate)",
              f"- days to reach min-n/day at this rate: {days_str}",
              "",
              "**Read:** GeckoTerminal free is THIN vs the May-14 bitquery firehose. If est sell-clusters/day "
              "is far below 100, raise `--max-pools`/`--pages`, loop more frequently, OR (future-optional, free) "
              "stream Bitquery Corecast into the same schema. The day-COUNT (>=14) is the binding axis for H-163, "
              "not raw volume — even thin days count if each yields enough independent cluster events.", ""]
    return "\n".join(lines)


def main():
    db = sqlite3.connect(str(DB))
    s = summary(db); d = daily(db); t = target(s)
    print(f"trades={s['trades']:,} wallets={s['wallets']:,} tokens={s['tokens']:,} pools={s['pools']:,} "
          f"span={s['span_days']:.2f}d runs={s['runs']} dup={s['dup_rate']:.1%} rl={s['rate_limited']} fail={s['http_fail']}")
    print(f"distinct days: {len(d)}  est sell-clusters/day: {t['est_sellclusters_per_day']:.1f} "
          f"(target {MIN_DAYS}+ days, {MIN_SELLCLUSTER_PER_DAY}+ clusters/day)")
    for row in d:
        print(f"  {row[0]}: trades={row[1]:,} wallets={row[2]:,} tokens={row[3]:,}")
    if "--write" in sys.argv:
        from firehose_collector import DATA
        (DATA.parent / "FIREHOSE_STATUS.md").write_text(render_md(s, d, t), encoding="utf-8")
        print(f"wrote {(DATA.parent / 'FIREHOSE_STATUS.md')}")
    db.close()


if __name__ == "__main__":
    main()
